<?php

namespace ScoperTest;

// autoload_classmap.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('ScoperTest\Composer\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php');
