<?php

namespace ScoperTest;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInitccb864d7c5b347ddde826f86ef855187
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('ScoperTest\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('ScoperTest\ComposerAutoloaderInitccb864d7c5b347ddde826f86ef855187', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \ScoperTest\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('ComposerAutoloaderInitccb864d7c5b347ddde826f86ef855187', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\ScoperTest\Composer\Autoload\ComposerStaticInitccb864d7c5b347ddde826f86ef855187::getInitializer($loader));
        $loader->register(\true);
        $filesToLoad = \ScoperTest\Composer\Autoload\ComposerStaticInitccb864d7c5b347ddde826f86ef855187::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
// autoload_real.php @generated by Composer
\class_alias('ScoperTest\ComposerAutoloaderInitccb864d7c5b347ddde826f86ef855187', 'ComposerAutoloaderInitccb864d7c5b347ddde826f86ef855187', \false);
