<?php

// autoload_static.php @generated by Composer
namespace ScoperTest\Composer\Autoload;

class ComposerStaticInitccb864d7c5b347ddde826f86ef855187
{
    public static $files = array('7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php', '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php', '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php', 'b648349f51c74416f621ceff7b4a0903' => __DIR__ . '/..' . '/resend/resend-php/src/resend-alias.php');
    public static $prefixLengthsPsr4 = array('S' => array('ScoperTest\Resend\\' => 17, 'ScoperTest\GuzzleHttp\Psr7\\' => 27, 'ScoperTest\GuzzleHttp\Promise\\' => 29, 'ScoperTest\GuzzleHttp\\' => 21, 'ScoperTest\Bamarni\Composer\Bin\\' => 31), 'P' => array('ScoperTest\Psr\Http\Message\\' => 27, 'ScoperTest\Psr\Http\Client\\' => 26));
    public static $prefixDirsPsr4 = array('ScoperTest\Resend\\' => array(0 => __DIR__ . '/..' . '/resend/resend-php/src'), 'ScoperTest\Psr\Http\Message\\' => array(0 => __DIR__ . '/..' . '/psr/http-factory/src', 1 => __DIR__ . '/..' . '/psr/http-message/src'), 'ScoperTest\Psr\Http\Client\\' => array(0 => __DIR__ . '/..' . '/psr/http-client/src'), 'ScoperTest\GuzzleHttp\Psr7\\' => array(0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src'), 'ScoperTest\GuzzleHttp\Promise\\' => array(0 => __DIR__ . '/..' . '/guzzlehttp/promises/src'), 'ScoperTest\GuzzleHttp\\' => array(0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src'), 'ScoperTest\Bamarni\Composer\Bin\\' => array(0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src'));
    public static $classMap = array('ScoperTest\Composer\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php');
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitccb864d7c5b347ddde826f86ef855187::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitccb864d7c5b347ddde826f86ef855187::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitccb864d7c5b347ddde826f86ef855187::$classMap;
        }, null, ClassLoader::class);
    }
}
