<?php

namespace ScoperTest;

// autoload_psr4.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('ScoperTest\Resend\\' => array($vendorDir . '/resend/resend-php/src'), 'ScoperTest\Psr\Http\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'), 'ScoperTest\Psr\Http\Client\\' => array($vendorDir . '/psr/http-client/src'), 'ScoperTest\GuzzleHttp\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'), 'ScoperTest\GuzzleHttp\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'), 'ScoperTest\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'), 'ScoperTest\Bamarni\Composer\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'));
